# SIB - Exercise 1

## 1.1) In this exercise, we will use the iris dataset. Load the "iris.csv" using the appropriate method for this file type (use the new functions from the package).

In [2]:
from si.io.csv_file import read_csv
#iris = read_csv("C:/Users/ricar/Desktop/Git_hub/SIB/si/datasets/iris/iris.csv",)
iris = read_csv("../datasets/iris/iris.csv", features=True, label=True)
print("Shape of iris dataset:",iris.shape())
print(iris.X)
print("Features:", iris.features)
print("Label:", iris.label)

Shape of iris dataset: (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]

## 1.2) Select the penultimate independent variable. What is the dimension of the resulting array?

In [3]:
pen_variable = iris.X[:,-2]
print("Number of dimensions:",pen_variable.ndim)
print("Shape", pen_variable.shape)

Number of dimensions: 1
Shape (150,)


## 1.3) Select the last 10 samples from the iris dataset. What is the mean of the last 10 samples for each independent variable/feature?

In [5]:
last_ten_samples = iris.X[-10:,:]

means= last_ten_samples.mean(axis=0)
print(means)

[6.45 3.03 5.33 2.17]


## 1.4) Select all samples from the dataset with values less than or equal to 6 for all independent variables/features. How many samples do you obtain?

In [24]:
import numpy as np
mask_samples = np.all(iris.X <= 6, axis=1)
filtered_samples = iris.X[mask_samples,:]
print("Number of samples:",filtered_samples.shape[0])   

Number of samples: 89


## 1.5) Select all samples with a class/label different from 'Iris-setosa'. How many samples do you obtain?

In [14]:
mask_not_iris_setosa = iris.y != "Iris-setosa"
samples_wo_setosa = iris.X[mask_not_iris_setosa,:]
print("Number of samples:",samples_wo_setosa.shape[0])

Number of samples: 100
